#!/bin/bash

#Instalando Audio
pacman -S pulseaudio pavucontrol--noconfirm

#Instalando Sudo
pacman -S sudo --noconfirm
#Editando arquivo sudoers
nano /etc/sudoers

#Instalando NetworkManager
pacman -S net-tools networkmanager --noconfirm
#Habilitando o NetworkManager
systemctl enable NetworkManager

#Instalando Xorg
pacman -S xorg --noconfirm

#Instalando xfce4
pacman -S xfce4 --noconfirm
#Instalando xfce-goodies
pacman -S xfce4-goodies --noconfirm
#Iniciando o xfce4
echo "exec startxfce4" >> ~/.xinitrc

#Instalando Lightdm
pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings lightdm-webkit2-greeter --noconfirm
#Habilitando Lightdm
systemctl enable lightdm

#Criando Diretorios
pacman -S xdg-user-dirs --noconfirm
xdg-user-dirs-update --noconfirm

#Instalando Gedit
pacman -S gedit --noconfirm

#Instalando Navegador
pacman -S chromium --noconfirm

#Instalando Extras
pacman -S kcalc okular gparted htop neofetch samba ntfs-3g nautilus arc-icon-theme archlinux-wallpaper nautilus-share dolphin dolphin-plugins firewalld unzip cups cups-filters cups-pdf cups-pk-helper system-config-printer print-manager nm-connection-editor --noconfirm

#Habilitando Fiweralld
systemctl enable firewalld

#Habilitando Cups
systemctl enable cups.service

#Criando Usuario Suporte
useradd -mG wheel,audio,video,games suporte
echo "SENHA DO USER SUPORTE"
passwd suporte
echo "REINICIE O COMPUTADOR E LOGUE COM O USER SUPORTE"
echo "DEPOIS BAIXE O ConfgInicial-02"
