#!/bin/bash

#Instalando Audio
pacman -S pulseaudio --noconfirm

#Instalando Sudo
pacman -S sudo --noconfirm

#Instalando Editor Nano
pacman -S nano --noconfirm
EDITOR=nano

#Editando arquivo sudoers
nano /etc/sudoers

#Instalando NetworkManager
pacman -S networkmanager --noconfirm

#Habilitando o NetworkManager
systemctl enable NetworkManager

#Instalando Xorg
pacman -S xorg --noconfirm

#Instalando xfce4
pacman -S xfce4 --noconfirm

#Instalando xfce-goodies
pacman -S xfce4-goodies --noconfirm

#Instalando Lightdm
pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings --noconfirm

#Iniciando o xfce4
echo "exec startxfce4" >> ~/.xinitrc

#Habilitando Lightdm
systemctl enable lightdm

#Criando Diretorios
pacman -S xdg-user-dirs --noconfirm
xdg-user-dirs-update --noconfirm

#Instalando Gedit
pacman -S gedit --noconfirm

#Instalando Navegador
pacman -S chromium --noconfirm

#Instalando Extras
pacman -S kcalc okular gparted samba nautilus nautilus-share firewalld unzip --noconfirm

#Habilitando Fiweralld
systemctl enable firewalld

#Criando Usuario Suporte
useradd -mG wheel,audio,video,games suporte
passwd suporte
echo "LOGUE COM O USER SUPORTE"
echo "E BAIXE O ConfgInicial-02"
