#!bin/bash

#Instalando Libre Office
sudo pacman -S libreoffice-fresh libreoffice-fresh-pt-br --noconfirm

#Instalando Yaourt
sudo pacman -S --needed base-devel wget yajl --noconfirm
sudo git clone https://aur.archlinux.org/package-query.git
sudo chmod 777 package-query
cd package-query
makepkg -sri
cd

sudo git clone https://aur.archlinux.org/yaourt.git
sudo chmod 777 yaourt
cd yaourt
makepkg -sri
cd

#Instalando Fontes MS
yaourt -S ttf-ms-fonts --noconfirm

#Instalando Google Chrome
yaourt -S google-chrome --noconfirm

#Instalando CPU-X
yaourt -S cpu-x --noconfirm

#Instalando tema Windows 10 no xfce4
yaourt -S xts-windows10-theme --noconfirm
xfce4-theme-switcher -t Windows-10-lb.tar.gz

#Instalando AnyDesk
yaourt -S anydesk-bin --noconfirm
systemctl enable anydesk
reboot
