#!/bin/bash

#Timezone
ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
hwclock --systohc

#Instalando Editor Nano
pacman -S nano --noconfirm
EDITOR=nano

#Localization
nano /etc/locale.gen
locale-gen
echo "LANG=pt_BR.UTF-8" >> /etc/locale.conf

#Teclado BR-ABNT2
echo "KEYMAP=br-abnt2" >> /etc/vconsole.conf

#Network Configuration
nano /etc/hostname
nano /etc/hosts

#Root Passaword
echo "DIGITE A SENHA DO ROOT"
passwd

#Boot Loader
pacman -Syyu
pacman -S grub
echo "INSTALE O GRUB"
echo "DEPOIS CONTINUE NO ConfigInicial-01"
