#!bin/bash

#Instalando Audio
pacman -S pulseaudio --noconfirm

#Instalando Sudo
pacman -S sudo --noconfirm

#Editando arquivo sudoers
nano /etc/sudoers

#Instalando NetworkManager
pacman -S networkmanager --noconfirm

#Habilitando o NetworkManager
systemctl enable NetworkManager

#Instalando Xorg
pacman -S xorg --noconfirm

#Instalando xfce4
pacman -S xfce4 --noconfirm

#Instalando xfce-goodies
pacman -S xfce4-goodies --noconfirm

#Instalando Lightdm
pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings lightdm-webkit2-greeter --noconfirm

#Iniciando o xfce4
echo "exec startxfce4" >> ~/.xinitrc

#Habilitando Lightdm
systemctl enable lightdm

#Criando Diretorios
pacman -S xdg-user-dirs --noconfirm
xdg-user-dirs-update --noconfirm

#Instalando Gedit
pacman -S gedit --noconfirm

#Instalando Navegador
pacman -S chromium --noconfirm

#Instalando Extras
pacman -S kcalc okular gparted samba nautilus arc-icon-theme plasma-workspace-wallpapers archlinux-wallpaper nautilus-share dolphin dolphin-plugins firewalld unzip cups cups-filters cups-pdf cups-pk-helper system-config-printer print-manager nm-connection-editor --noconfirm

#Habilitando Fiweralld
systemctl enable firewalld

#Habilitando Cups
systemctl enable cups.service

#Criando Usuario Suporte
useradd -mG wheel,audio,video,games suporte
echo "SENHA DO USER SUPORTE"
passwd suporte
echo "LOGUE COM O USER SUPORTE"
echo "E BAIXE O ConfgInicial-02"
